### ISSUE TITLE
New Images need to be recentered

### ISSUE THREAD

**Issue by Larry-Schultz** [Larry-Schultz/FFTB_Viewer#26]
The new chocobo images show up on the live page off-center.

**Comment by OtherBrand** [comment]
Mostly happening to the new chocobo images.

**Comment by OtherBrand** [comment]
Looks like its happening to more :(

**Comment by OtherBrand** [comment]
I think the fix may be to have custom configs for the janky files that tell the UI how to manually fix their appearance.

**Comment by Larry-Schultz** [comment]
No need for janky config.  Just use flexbox to center all images.

I have a fix in local.  Just need to push to prod.

**Comment by Larry-Schultz** [comment]
While the correctly working images don't look quite as nice, the images having issues look far better.

Fix has been confirmed in prod, finally closing out this old bug.
